spring:

  kafka:
#    kafka on my macbook
    bootstrap-servers: '192.168.1.129:9094'
    consumer:
      enable-auto-commit: true
    producer:
      properties:
#        how long producer will block the thread
        "max.block.ms" : 10000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer