spring:

  application:
    name: Spring boot skb

  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:file:~/fileDb"
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    database: h2

  h2:
    console:
      enabled: true
      path: /h2

  kafka:
    bootstrap-servers: '192.168.1.129:9094'
    consumer:
      enable-auto-commit: true
    producer:
      properties:
        "max.block.ms" : 10000
        #      transaction-id-prefix: "kafka-reg-tx"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  thymeleaf:
    cache: false

  web:
    locale: en_US