spring:

  application:
    name: Spring boot skb

  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:testDb"
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    database: h2

  kafka:
    bootstrap-servers: '192.168.1.129:9094'
    consumer:
      enable-auto-commit: true
    producer:
      transaction-id-prefix: "kafka-reg-tx"

