spring:

  application:
    name: Spring boot hyip project

  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:file:~/fileDb"
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    database: h2

  h2:
    console:
      enabled: true
      path: /h2

  liquibase:
    change-log: 'classpath:/config/liquibase/changelog/0.0.1-Init.yaml'
    enabled: true

  thymeleaf:
    cache: false

#  for @Scheduled
  task:
    scheduling:
      pool:
        size : 5
  web:
    locale: en_US

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO