spring:

  kafka:
#    kafka on my macbook
    bootstrap-servers: 'eprupetw10aa:30903, eprupetw10aa:30448,  eprupetw10aa:30805'
    producer:
      client-id: mainAppProducer
#      buffer-memory : 32000000 default ok
      acks : 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      transaction-id-prefix: mainAppTx-
      properties:
        max.block.ms: 10000

    listener:
      poll-timeout: 10000
      concurrency: 1

    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
      client-id: mainAppConsumer
      group-id: hyip-group
      max-poll-records: 50

    #topic to send users for approval
    approvalTopic: userForApproval
    #topic where to get confirmation from
    processedTopic: processedUsers

logging:
  level:
    org.springframework.kafka.transaction: debug