changeSet:
  id: init-upload
  author: liquibase
  changes:
    - loadData:
        columns:
          - column:
              name:  name
              type:  varchar
        commentLineStartsWith:  //
        encoding:  UTF-8
        file:  config/liquibase/data/authority.csv
        quotchar:  ''''
        relativeToChangelogFile:  false
        schemaName:  public
        separator:  ;
        tableName:  authority_t
        usePreparedStatements:  true

